# Generated by Django 5.1.15 on 2026-10-05 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('industry_category', models.CharField(max_length=128)),
                ('avg_months_to_complete', models.PositiveIntegerField(default=6)),
                ('badge', models.CharField(blank=True, default='High Demand', max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['industry_category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='careers.career')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('taxonomy', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze'), ('EVALUATE', 'Evaluate'), ('CREATE', 'Create')], default='APPLY', max_length=16)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='careers.competencyarea')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('competency_area', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='careers.skill')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('provider_name', models.CharField(max_length=128)),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video / Lecture'), ('ARTICLE', 'Article / Guide'), ('DOCUMENTATION', 'Official Documentation'), ('BOOK', 'Legally Free Book / Text'), ('INTERACTIVE_LAB', 'Interactive Practice / Lab'), ('SIMULATION', 'Simulation / Sandbox')], max_length=32)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('is_completely_free', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('DEGRADED', 'Degraded / Broken')], default='DRAFT', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.topic')),
            ],
            options={
                'ordering': ['-verification_status', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_strict', models.BooleanField(default=True, help_text='Strict blockers must be completed before unlocking downstream skill.')),
                ('prerequisite_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_links', to='careers.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='careers.skill')),
            ],
            options={
                'unique_together': {('skill', 'prerequisite_skill')},
            },
        ),
    ]
