# Generated by Django 5.1.15 on 2026-10-05 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('scenario_brief', models.TextField(help_text='Authentic, real-world workplace scenario.')),
                ('deliverable_spec', models.TextField(help_text='Explicit output requirements (e.g. GitHub URL, PDF spreadsheet).')),
                ('rubric_schema', models.JSONField(default=list, help_text='List of evaluation criteria with weights and 1-4 descriptive anchors.')),
                ('is_capstone', models.BooleanField(default=False, help_text='Capstone projects are hard gates for career readiness.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='careers.skill')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_url', models.URLField(help_text='Public URL to deliverable (GitHub, Google Docs, Figma, R2 storage).', max_length=1024)),
                ('notes', models.TextField(blank=True, help_text='Student reflections or execution notes.')),
                ('learner_self_eval', models.JSONField(blank=True, default=dict)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('EVALUATED', 'Evaluated (Feedback Ready)'), ('NEEDS_REVISION', 'Needs Revision'), ('APPROVED', 'Approved / Mastered')], default='SUBMITTED', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
