# Generated by Django 5.1.15 on 2026-10-05 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('passing_score_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('time_limit_minutes', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='careers.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(help_text="User selected answers: {'question_id': 'selected_id'}")),
                ('score_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_passed', models.BooleanField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Single Answer'), ('SCENARIO', 'Situational Case-Study Judgment')], default='MCQ', max_length=32)),
                ('options', models.JSONField(help_text="List of choices: [{'id': 'A', 'text': '...'}, ...]")),
                ('correct_answer_id', models.CharField(help_text="ID of correct option (e.g. 'A')", max_length=16)),
                ('explanation', models.TextField(help_text='Pedagogical explanation shown upon completion.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
