# Generated by Django 5.1.15 on 2026-10-05 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committed_hours_per_week', models.PositiveIntegerField(default=10)),
                ('projected_completion_date', models.DateField(blank=True, null=True)),
                ('readiness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='careers.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'career')},
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked (Prerequisites Incomplete)'), ('AVAILABLE', 'Available to Start'), ('IN_PROGRESS', 'In Progress (Studying)'), ('PRACTICING', 'Practicing (Drills / Projects)'), ('ASSESSED', 'Assessed (Evaluation Complete)'), ('MASTERED', 'Mastered & Verified')], default='LOCKED', max_length=24)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progresses', to='roadmaps.userroadmap')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='careers.skill')),
            ],
            options={
                'ordering': ['skill__title'],
                'unique_together': {('roadmap', 'skill')},
            },
        ),
    ]
